### ISSUE TITLE
The data POSTed should be retrievable in the next request.

### ISSUE THREAD

**Issue by donriddo** [lumie31/hackerbay-university#1]
https://github.com/lumie31/hackerbay-university/blob/f98cfae8b1a657ace4d7081acdee6de07b1b0baa/server.js#L13

Create a variable that's outside API scope and save the data there, once you're done doing that return the same data in the request.

**Comment by lumie31** [comment]
I moved the variable outside the scope of the API and made changes to the `GET` and `POST` request on the `/data` route

**Comment by donriddo** [comment]
@lumie31 `GET /data` will always return `Any string`.

In the `POST /data`, you should set `data` to `req.body.data`, then with this, `data` will be retrievable on calling `GET` later. Let me know if you have any questions.

**Comment by lumie31** [comment]
I have made the necessary changes pertaining to this issue. Thank you

**Comment by donriddo** [comment]
Good work so far!
