### ISSUE TITLE
This is bad design

### ISSUE THREAD

**Issue by donriddo** [lumie31/hackerbay-university#7]
https://github.com/lumie31/hackerbay-university/blob/dd076f687cb21c29fd1a3da6d45f95f5070a4377/server.js#L80

`User.beforeValidate` should just be setup once and not every time you create a new user. Move this entire block to outside of your `POST /user/signup`. Also, the `connection.sync` is not to be in the user create block. In fact, the only thing that should be in your `app.post('/user/signup')` block is just `User.create` or `User.findOrCreate` or whatever logic you are using.

**Comment by lumie31** [comment]
I have revised the logic and made the necessary changes that you pointed out.
