### ISSUE TITLE
Make sure your errors are handled.

### ISSUE THREAD

**Issue by donriddo** [lumie31/hackerbay-university#8]
https://github.com/lumie31/hackerbay-university/blob/dd076f687cb21c29fd1a3da6d45f95f5070a4377/server.js#L129

Split this line into `if..else..if`, Check `if error` first and return `Error logging in`, then check `if !user` and then return `Incorrect Email/Password`. With this, your client can get better interactions with your system.

**Comment by lumie31** [comment]
This has been fixed. Thank you
