### ISSUE TITLE
Never push commented code. Comments are fine.

### ISSUE THREAD

**Issue by donriddo** [lumie31/hackerbay-university#9]
https://github.com/lumie31/hackerbay-university/blob/dd076f687cb21c29fd1a3da6d45f95f5070a4377/server.js#L29

Don't comment previous tasks out. Remember, you are to build on them. Only remove them if you think it will interfere with your new approach and then, you might actually be doing something wrong because your system shouldn't be restricting to the little changes you are making.

**Comment by lumie31** [comment]
I've fixed this. I deleted task-1 from the task-2 branch and left it in the master branch, so when I merge to the master, task-1 will be there
